{% set name = "festim" %}
{% set version = "1.4.1.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/festim-{{ version }}.tar.gz
  sha256: 9fb3d33cc7cf8e093892ca06ee0584c5b4de7b3f586f19424fc9ebc9c114ba42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=7.0.5
    - pip
  run:
    - python >={{ python_min }}
    - fenics

test:
  imports:
    - festim
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/festim-dev/FESTIM
  summary: Finite element simulations of hydrogen transport
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RemDelaporteMathurin
