{% set name = "festim" %}
{% set version = "2.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/festim-{{ version }}.tar.gz
  sha256: c51cd3d6ec27e48266c08987b982fec5c16c38100c85a24037a1c6750c400aef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=7.0.5
    - pip
  run:
    - python >={{ python_min }}
    - fenics-dolfinx >=0.9,<=0.10
    - scifem >=0.2.13
    - adios4dolfinx
    - tqdm

test:
  imports:
    - festim
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/festim-dev/FESTIM
  summary: Finite element simulations of hydrogen transport
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RemDelaporteMathurin
