{% set name = "festim" %}
{% set version = "2.2rc2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/festim-{{ version }}.tar.gz
  sha256: b93884dc3f3100530a1a91e268dadf52af64e421c14e96e596d8f98ad85a9d61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=7.0.5
    - pip
  run:
    - python >={{ python_min }}
    - fenics-dolfinx >=0.10,<=0.11
    - scifem >=0.2.13
    - io4dolfinx
    - tqdm

test:
  imports:
    - festim
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/festim-dev/FESTIM
  summary: Finite element simulations of hydrogen transport
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RemDelaporteMathurin
